#-------------------------------
# General Site Settings

title: MrDemonWolf
name: MrDemonWolf
description: test
email: demonwolf@demonwolfdev.com
#url: https://start.mrdemonwolf.me
url: http://localhost:3000  #Dev URL

#-------------------------------
# SEO Section

seo:
  twitter-creator: 'https://www.twitter.com/mrdemonwolf'
  twitter-site: 'https://www.twitter.com/mrdemonwolf'
  type: 'website'

#-------------------------------
# Google Analytics Section

google-analytics-ua: UA-xxxx-xx

#-------------------------------
# Link Section

sites: 
- {name: 'Freelancing', url: 'https://www.mrdemonwolf.me/'}
- {name: 'Community', url: 'https://www.demonwolfdev.com/'}
- {name: 'Community Assets', url: 'https://assets.demonwolfdev.com/'}

webmaster: 
- {name: 'Namecheap', url: 'https://www.namecheap.com/'}
- {name: 'Cloudflare', url: 'https://www.cloudflare.com/'}
- {name: 'Let’s Encrypt', url: 'https://letsencrypt.org/'}
- {name: 'Google Analytics', url: 'https://analytics.google.com/analytics/web/'}
- {name: 'Google Web master', url: 'https://www.google.com/webmasters/tools/home/'}

services: 
- {name: 'Vultr', url: 'http://www.vultr.com/?ref=7093526'}
- {name: 'Logicweb', url: 'https://www.logicweb.com/'}
- {name: 'Veesp', url: 'https://veesp.com/'}
- {name: 'Cloud at Cost', url: 'https://panel.cloudatcost.com/login.php'}

resources: 
- {name: 'Ask Ubuntu', url: 'https://askubuntu.com/'}
- {name: 'Digitalocean Tutorials', url: 'https://www.digitalocean.com/community/tutorials/'}
- {name: 'Stackoverflow', url: 'https://stackoverflow.com/'}
- {name: 'Makerbook', url: 'https://makerbook.net/'}
- {name: 'Resource Cards', url: 'https://resourcecards.com/'}

webtools: 
- {name: 'Adobe.CC', url: 'https://example.com'}
- {name: 'LOL Colors', url: 'https://example.com'}
- {name: 'CSS Matic', url: 'https://example.com'}
- {name: 'Contrast Checker', url: 'https://example.com'}
- {name: 'Dirtymarkup', url: 'https://example.com'}
- {name: 'Font Awesome', url: 'https://example.com'}
- {name: 'Optimizilla', url: 'https://example.com'}
- {name: 'Dans Tools', url: 'https://example.com'}
- {name: 'Corporate Ipsum', url: 'https://example.com'}

github: 
- {name: 'MrDemonWolf Github', url: 'https://github.com/mrdemonwolf/'}
- {name: 'DemonWolfDev Github', url: 'https://github.com/demonwolfdev/'}

#-------------------------------
search: https://www.google.com/search