#-------------------------------
# General Site Settings

title: MrDemonWolf
name: MrDemonWolf
url: https://start.mrdemonwolf.me
#url: http://localhost:3000  #Dev URL
search: https://www.google.com/search

#-------------------------------
# SEO Section

seo:
  twitter-creator: 'https://www.twitter.com/mrdemonwolf'
  twitter-site: 'https://www.twitter.com/mrdemonwolf'
  type: 'website'

#-------------------------------
# Link Section

sites:
- {name: 'Freelancing', url: 'https://mrdemonwolf.me/'}
- {name: 'Community', url: 'https://www.demonwolfdev.com/'}
- {name: 'Community Assets', url: 'https://assets.demonwolfdev.com/'}

webmaster:
- {name: 'Namecheap', url: 'https://www.namecheap.com/'}
- {name: 'Cloudflare', url: 'https://www.cloudflare.com/'}
- {name: 'Let’s Encrypt', url: 'https://letsencrypt.org/'}
- {name: 'Google Analytics', url: 'https://analytics.google.com/analytics/web/'}
- {name: 'Google Web master', url: 'https://www.google.com/webmasters/tools/home/'}

services:
- {name: 'Vultr', url: 'http://www.vultr.com/?ref=7093526'}
- {name: 'Logicweb', url: 'https://www.logicweb.com/'}
- {name: 'Veesp', url: 'https://veesp.com/'}
- {name: 'Cloud at Cost', url: 'https://panel.cloudatcost.com/login.php'}

resources:
- {name: 'Ask Ubuntu', url: 'https://askubuntu.com/'}
- {name: 'Digitalocean Tutorials', url: 'https://www.digitalocean.com/community/tutorials/'}
- {name: 'Stackoverflow', url: 'https://stackoverflow.com/'}
- {name: 'Makerbook', url: 'https://makerbook.net/'}
- {name: 'Resource Cards', url: 'https://resourcecards.com/'}

webtools:
- {name: 'Adobe.CC', url: 'https://color.adobe.com/explore/most-popular/?time=all'}
- {name: 'LOL Colors', url: 'http://www.lolcolors.com/'}
- {name: 'CSS Matic', url: 'http://www.cssmatic.com/'}
- {name: 'Contrast Checker', url: 'http://webaim.org/resources/contrastchecker/'}
- {name: 'Dirtymarkup', url: 'https://dirtymarkup.com/'}
- {name: 'Font Awesome', url: 'http://fontawesome.io/'}
- {name: 'Optimizilla', url: 'http://optimizilla.com/'}
- {name: 'Dans Tools', url: 'http://www.danstools.com/'}
- {name: 'Corporate Ipsum', url: 'http://www.cipsum.com/'}
- {name: 'CDN JS', url: 'https://cdnjs.com/'}
- {name: 'Git Simple Guide', url: 'http://rogerdudler.github.io/git-guide/'}
github:
- {name: 'MrDemonWolf Github', url: 'https://www.github.com/mrdemonwolf/'}
- {name: 'DemonWolfDev Github', url: 'https://www.github.com/demonwolfdev/'}

#-------------------------------
