#-------------------------------
# General Site Settings

title: MrDemonWolf
name: MrDemonWolf
description: test
email: demonwolf@demonwolfdev.com
#url: https://start.mrdemonwolf.me
url: http://localhost:3000  #Dev URL

#-------------------------------
# SEO Section

seo:
  twitter-creator: 'https://www.twitter.com/mrdemonwolf'
  twitter-site: 'https://www.twitter.com/mrdemonwolf'
  type: 'website'

#-------------------------------
# Google Analytics Section

google-analytics-ua: UA-xxxx-xx

#-------------------------------
# Link Section

sites: 
- {name: 'Freelancing', url: 'https://www.mrdemonwolf.me/'}
- {name: 'Community', url: 'https://www.demonwolfdev.com/'}
- {name: 'Community Assets', url: 'https://assets.demonwolfdev.com/'}

webmaster: 
- {name: 'Namecheap', url: 'https://www.namecheap.com/'}
- {name: 'Cloudflare', url: 'https://www.cloudflare.com/'}
- {name: 'Let’s Encrypt', url: 'https://letsencrypt.org/'}
- {name: 'Google Analytics', url: 'https://analytics.google.com/analytics/web/'}
- {name: 'Google Web master', url: 'https://www.google.com/webmasters/tools/home/'}

services: 
- {name: 'Vultr', url: 'http://www.vultr.com/?ref=7093526'}
- {name: 'Veesp', url: 'https://www.logicweb.com/'}
- {name: 'Test', url: 'https://example.com'}
- {name: 'Test2', url: 'https://example.com'}

resources: 
- {name: 'Test', url: 'https://example.com'}
- {name: 'Test2', url: 'https://example.com'}
- {name: 'Test', url: 'https://example.com'}
- {name: 'Test', url: 'https://example.com'}
- {name: 'Test', url: 'https://example.com'}

webtools: 
- {name: 'Test', url: 'https://example.com'}
- {name: 'Test2', url: 'https://example.com'}
- {name: 'Test', url: 'https://example.com'}
- {name: 'Test', url: 'https://example.com'}
- {name: 'Test', url: 'https://example.com'}
- {name: 'Test2', url: 'https://example.com'}
- {name: 'Test', url: 'https://example.com'}
- {name: 'Test', url: 'https://example.com'}
- {name: 'Test', url: 'https://example.com'}

github: 
- {name: 'Test', url: 'https://example.com'}
- {name: 'Test2', url: 'https://example.com'}

#-------------------------------
search: https://www.google.com/search